#spring:
#  application:
#    name: tay-java-app
#  profiles:
#    active: @spring.profiles.active@

#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:${server.port}
#    title: API Document
#    version: 1.0.0
