server.port=80
spring.config.activate.on-profile=dev
openapi.service.api-docs=api-service
openapi.service.server=http://localhost:${server.port}
openapi.service.title=${API_TITLE:DUMMY-API-TITLE}
openapi.service.version=1.0.0